name: peristock
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  android_intent_plus: ^3.1.1+1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  go_router: ^5.0.1
  hooks_riverpod: ^2.0.0-dev.9
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  jwt_decoder: ^2.0.1
  phosphor_flutter: ^1.4.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  supabase_flutter: ^0.3.3
  uni_links: ^0.5.1
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  riverpod_annotation: ^1.0.6

flutter:
  uses-material-design: true
  generate: true
