name: peristock
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  android_intent_plus: ^3.1.6
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  dio: ^5.0.2
  equatable: ^2.0.5
  file: ^6.1.4
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  go_router: ^6.2.0
  hooks_riverpod: ^2.3.1
  image_picker: ^0.8.7
  intl: ^0.17.0
  json_annotation: ^4.8.0
  jwt_decoder: ^2.0.1
  phosphor_flutter: ^1.4.0
  riverpod_annotation: ^2.0.2
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  uni_links: ^0.5.1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
  generate: true
