import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:gap/gap.dart';
import 'package:go_router/go_router.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:peristock/app/theme/theme.dart';
import 'package:peristock/products/domain/products.dart';
import 'package:peristock/products/presentation/components/components.dart';
import 'package:peristock/products/presentation/processors/processors.dart';
import 'package:peristock/products/presentation/providers/product_item.dart';
import 'package:peristock/products/presentation/providers/products_collection.dart';
import 'package:peristock/shared/presentation/layouts/layouts.dart';
import 'package:peristock/shared/presentation/widgets/widgets.dart';

part 'products_create.dart';
part 'products_edit.dart';
part 'products_list.dart';
part 'products_read.dart';
